#!/usr/bin/env bash

rm /autograder/submission/assignment_name/test_assignment.py

cp /autograder/source/test_assignment.py /autograder/submission/assignment_name/

cd /autograder/submission/

poetry install

poetry run python3 /autograder/source/run_tests.py